<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ArsExtractum.App</RootNamespace>
    <AssemblyName>ArsExtractum</AssemblyName>
    <ApplicationIcon />
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ArsExtractum.Core/ArsExtractum.Core.csproj" />
    <ProjectReference Include="../ArsExtractum.PdfPig/ArsExtractum.PdfPig.csproj" />
  </ItemGroup>

</Project>
